version: '3.9'
services:
  sh: &base
    image: node:lts-alpine
    volumes:
      - .:/opt/code
      - $HOME/.aws:/root/.aws
    working_dir: /opt/code
    environment:
      - AWS_DEFAULT_REGION=ap-southeast-2
      - AWS_PROFILE
    command: sh

  install:
    <<: *base
    command: npm install

  lint:
    <<: *base
    command: npm run lint

  test:
    <<: *base
    command: npm test

  deploy:
    <<: *base
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SECURITY_TOKEN
      - AWS_SESSION_TOKEN
      - AWS_DEFAULT_REGION=ap-southeast-2
      - AWS_PROFILE
    command: npm run deploy
